In [1]:
from csv import reader
data = list(reader(open("EPL_Set.csv")))
import pandas as pd

In [6]:
def FIFA_EPL_Table(Year):
    Season = []                 # Create empty season list
    for f in data:              # looping through FIFA dataset
        if f[-1] == Year:       # Check if season column of FIFA dataset matches with Functions input
            Season.append(f)    # If it matches, append the FIFA dataset rows in season list
            
    teams = []                  # Create an empty team list
    for i in data:              # loop through FIFA dataset
        season = i[-1]          # Define the Season column 
        if season == Year:      # Check if season column matches with functions input
            if i[2] not in teams: # Hometeam Column fields not present in teams list
                teams.append(i[2]) # if true append the team name to the teams list
                
    table = []                     # Create an empty table
    for i in teams:                # looping through teams list 
        table.append([i,0,0,0,0,0,0,0,0]) # append 8 zeros with every team to a table list


    for s in Season:                      # loop through the input season datset
        Home = s[2]                       # define Home team column
        Away = s[3]                       # define Away team column
        Hgoals = int(s[4])                # define Goal scored column 
        Agoals = int(s[5])                # define goal conceived column
        results = s[6]                    # define results(FTR) column

        for t in table:                   # Inside the input season dataset loop through an empty table
            if results == "H":            # check If Home team wins 
                if Home == t[0]:          # 
                    t[1] += 1             # add increment of one every time it played a mathch         
                    t[2] += 1             # add increment of one every time it wins
                    t[5] += Hgoals        # add number of goals scored 
                    t[6] += Agoals        # add number of goals Conceived 
                    t[7] += (Hgoals - Agoals) # Find the goal difference
                    t[8] += 3                 # Give 3 points to every team who won the match
                if Away == t[0]:              # Away team column 
                    t[1] += 1                 # Add increment of 1 of every match in a Mathces played column
                    t[3] += 1                 # Add increment of 1 of every loss match  
                    t[5] += Agoals            # add goal scored 
                    t[6] += Hgoals            # add goal conceived
                    t[7] += (Agoals - Hgoals) # goal difference
                    t[8] += 0                 # add incement of zero whenever it lose a mathch as an away team 
                    
            elif results == "A":              # If the Team won a match as an Away Team  
                if Home == t[0]:              # If the Home team name matches with the table team name 
                    t[1] += 1                 # add increment of one every match play in a MP column     
                    t[3] += 1                 # add increment one of every loss match as an home team
                    t[5] += Hgoals            # add increment of number of goals scored as Home team 
                    t[6] += Agoals            # add increment of number of goals conceived as home team
                    t[7] += (Hgoals - Agoals) 
                    t[8] += 0                 # add increment of zero because it loses as an home team
                if Away == t[0]:              # If away team column names mathces with table team column names 
                    t[1] += 1                 # add increment of 1 in table Matches played column 
                    t[2] += 1                 # add increment of 1 in table wins column 
                    t[5] += Agoals            # add number of goals scored in goal scored column
                    t[6] += Hgoals            # add number of goals conceived in goal conceived column
                    t[7] += (Agoals - Hgoals) # goal difference
                    t[8] += 3                 # give 3 points to every team won 
                    
            elif results == "D":              # if results equal to draw
                if Home == t[0]:              # check home team column matches with table team
                    t[1] += 1                 # increment of 1 in matches played column
                    t[4] += 1                 # increment of 1 in draw column
                    t[5] += Hgoals            # increment of goals scored as an home team
                    t[6] += Agoals            # increment of goals conceived as an home team
                    t[7] += (Hgoals - Agoals) # goal difference
                    t[8] += 1                 # add increment of 1 point to every draw
                if Away == t[0]:              # check the away team column 
                    t[1] += 1                 # add increment of 1 in matches played
                    t[4] += 1                 # add increment of 1 in draw column
                    t[5] += Agoals            # add increment of goal scored in column GF as an Away team
                    t[6] += Hgoals            # add increment of goal conceived in column GC as an away team
                    t[7] += (Agoals - Hgoals) # goal difference
                    t[8] += 1                 # add increment of 1 point as an away team            
                    
                                 
                    
    index = []
    for i in range(1,21):
        index.append(i)                
    EPL_Table = pd.DataFrame(table)           # convert the table into dataframe
    EPL_Table.columns = ["Club", "MP","W","L","D","GF","GA","GD","Pts"] # Name the columns
    EPL_Table = EPL_Table.sort_values(by="Pts",ascending=False).reset_index().drop("index",axis=1)
    EPL_Table.insert(loc=0, column='Rank', value=index)
    
    return EPL_Table # return the table in data frame

In [7]:
FIFA_EPL_Table("2007-08")

    Rank           Club  MP   W   L   D  GF  GA  GD  Pts
0      1     Man United  38  27   5   6  80  22  58   87
1      2        Chelsea  38  25   3  10  65  26  39   85
2      3        Arsenal  38  24   3  11  74  31  43   83
3      4      Liverpool  38  21   4  13  67  28  39   76
4      5        Everton  38  19  11   8  55  33  22   65
5      6    Aston Villa  38  16  10  12  71  51  20   60
6      7      Blackburn  38  15  10  13  50  48   2   58
7      8     Portsmouth  38  16  13   9  48  40   8   57
8      9       Man City  38  15  13  10  45  53  -8   55
9     10       West Ham  38  13  15  10  42  50  -8   49
10    11      Tottenham  38  11  14  13  66  61   5   46
11    12      Newcastle  38  11  17  10  45  65 -20   43
12    13  Middlesbrough  38  10  16  12  43  53 -10   42
13    14          Wigan  38  10  18  10  34  51 -17   40
14    15     Sunderland  38  11  21   6  36  59 -23   39
15    16         Bolton  38   9  19  10  36  54 -18   37
16    17         Fulham  38   8  18  12  38  60 -22   36
17    18        Reading  38  10  22   6  41  66 -25   36
18    19     Birmingham  38   8  19  11  46  62 -16   35
19    20          Derby  38   1  29   8  20  89 -69   11